name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  PYTHON_RUN_ENV: test
  PYTHON_VERSION: 3.13

jobs:
  display-env-var:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
          cache: pip
      - name: Run python script
        run: python main.py